#!/usr/bin/env ruby
# encoding: utf-8

require 'fileutils'
require 'logger'
require 'inotify'

#Only allow one running instance
exit unless File.new("/tmp/blink_record.lock", "w+").flock(File::LOCK_NB | File::LOCK_EX )

$version = 0.2
$logger = Logger.new(File.expand_path("~/.blink_record.log"), 4, 1024000)

class BlinkRC
  attr_accessor :settings,:path

  def initialize(path="~/.blink_recordrc")
    path = File.expand_path(path)
    @path = path
    @settings = Hash.new
    if(File.exists?(path))
      $logger.info "Reading from config file."
      File.open(path) do |file|
        file.readlines.each do |line|
          l = line.split(":")
          @settings[l[0].strip] = l[1].strip
        end
      end
    end
  end
end

class DemoFile
  attr_reader :nick, :map, :duration, :time_str, :time

  def initialize(path)
    raise "Path to demo file cannot be empty" unless path
    parse(path)
  end

  def parse(demo_file_path)
    raw_data = File.open(demo_file_path, "r"){|file| file.sysread(4096)}
    # https://developer.valvesoftware.com/wiki/DEM_Format
    demodata = raw_data.unpack("A8/I/I/A260/A260/A260/A260/f/I/I/I")
    @nick = demodata[4]
    @map = demodata[5]
    @duration = demodata[7]
    @time = File.mtime(demo_file_path)
    #Same weird format as prec, added seconds though.
    @time_str = File.mtime(demo_file_path).strftime("%Y%m%d_%H%M%S")
  end

  #To ease debugging
  def inspect
    "<%s nick=%s map=%s duration=%s time=%s time_str=%s>" % [
      self.class,
      @nick,
      @map,
      @duration,
      @time,
      @time_str,
    ]
  end
end

class BlinkRecord
  attr_reader :demo_dir

  def initialize
    blink_cfg = BlinkRC.new
    @tf2_dir = blink_cfg.settings["tf2_dir"]
    unless @tf2_dir
      error_msg = "Could not find blink_recordrc"
      $logger.error error_msg
      system("zenity --text=\"#{error_msg}\" --error")
      abort error_msg
    end
    @move_path = blink_cfg.settings["move_path"]
    @demo_dir = File.join @tf2_dir, "tf/"
  end

  def move_demo_file(filename)
    #Begin the demo parsing
    begin
      demo_file_path = File.join(@demo_dir, filename)
      $logger.info demo_file_path
      d = DemoFile.new(demo_file_path)
      $logger.info d
      new_file_path = File.join(@move_path, "#{d.time_str}_#{d.map}-#{d.nick}")
      new_file_path += "_#{(d.duration/60).to_i}m#{(d.duration%60).to_i}s.dem"
      puts demo_file_path + " ---> " + new_file_path
      $logger.info demo_file_path + " ---> " + new_file_path
      FileUtils.mv(demo_file_path, new_file_path)
    rescue => e
      $stderr.puts(e)
      $logger.error(e)
      system("zenity --text=\"Could not move demo: #{demo_file_path}\n"\
             "message: #{e.message}\" --error")
      abort("Could not move #{demo_file_path}. Aborting.")
    end
  end
end

if ARGV.size ==  1
  if ARGV[0] == "--version" || ARGV[0] == "-v"
    puts "blink_record binary version #{$version}"
    exit 0
  end
end

begin

  blink_record = BlinkRecord.new
  i = Inotify.new

  #setup the inotify listening thread
  t = Thread.new do
    i.each_event do |ev|
      if ev.name =~ /demo_\d\d\.dem/
        $logger.info ev.inspect
        blink_record.move_demo_file(ev.name)
      end
    end
  end

  begin
    #Only show newly written closed files
    i.add_watch(blink_record.demo_dir, Inotify::CLOSE_WRITE)
  rescue => e
    $logger.error error_msg
    system("zenity --text\"Error in inotify.\n#{e.message}\" --error")
  end

  t.join
  exit 0

rescue => e
  $logger.error(e)
  system("zenity --text\"Unexpected error.\n#{e.message}\" --error")
  abort("Unexpected error: #{e.message}")
end
