#!/usr/bin/env ruby
# encoding: utf-8

require 'fileutils'
require 'logger'
require 'inotify'

#Only allow one running instance
exit unless File.new("/tmp/blink_record.lock", "w+").flock(File::LOCK_NB | File::LOCK_EX )

$version = 0.3
$logger = Logger.new(File.expand_path("~/.blink_record.log"), 1, 1024000)
$logger.level = Logger::INFO

#Reads the config from file.
class BlinkRC
  attr_accessor :settings,:path

  def initialize(path="~/.blink_recordrc")
    path = File.expand_path(path)
    @path = path
    @settings = Hash.new
    if(File.exists?(path))
      $logger.debug "Reading from config file."
      File.open(path) do |file|
        file.readlines.each do |line|
          l = line.split(":")
          @settings[l[0].strip] = l[1].strip
        end
      end
    end
  end
end

#This class represents a .dem file. It parses the header of the file to object
#variables.
class DemoFile
  attr_reader :nick, :map, :duration, :time_str, :time, :ticks

  #Initializes the class.
  def initialize(path)
    raise "Path to demo file cannot be empty" unless path
    parse(path)
  end

  #Parse the header of .dem file and stores them in object variables.
  def parse(demo_file_path)
    raw_data = File.open(demo_file_path, "r"){|file| file.sysread(4096)}
    # https://developer.valvesoftware.com/wiki/DEM_Format
    demodata = raw_data.unpack("A8/I/I/A260/A260/A260/A260/f/I/I/I")
    @nick = demodata[4]
    @map = demodata[5]
    @duration = demodata[7]
    @ticks = demodata[8]
    #Stamped at end of demo
    @time = File.mtime(demo_file_path)
    #Same weird format as prec, added seconds though.
    @time_str = File.mtime(demo_file_path).strftime("%Y%m%d_%H%M%S")
  end

  #To ease debugging
  def inspect
    "<%s nick=%s map=%s duration=%s time=%s time_str=%s>" % [
      self.class,
      @nick,
      @map,
      @duration,
      @time,
      @time_str,
    ]
  end
end

#Class that handles demo moving and screenshots/bookmarks logic.
class BlinkRecord
  attr_reader :demo_dir

  #Initialized the class by reading config and assigning object variables.
  def initialize
    @screenshots = Array.new
    blink_cfg = BlinkRC.new
    @tf2_dir = blink_cfg.settings["tf2_dir"]
    unless @tf2_dir
      error_msg = "Could not find blink_recordrc"
      $logger.error error_msg
      system("zenity --text=\"#{error_msg}\" --error")
      abort error_msg
    end
    @move_path = blink_cfg.settings["move_path"]
    @demo_dir = File.join @tf2_dir, "tf/"
    #Amount of time(s) for status and score screenshots in the beginning/end.
    @grace = blink_cfg.settings["grace"].to_i rescue 0
  end

  #Search for screenshot files in @demo_dir/screenshots/ with the name
  #blink_bmark*.jpg and a timestamp that is in the range of demo file.
  #Decides if the screenshot is a status,scoreboard or a bookmark and move
  #files to @move_path with sane name and adds line too bookmark.txt if it is a
  #bookmark.
  def find_and_handle_screenshots(base_name, demo_start, demo_end, tps)
    ss_path = File.join(@demo_dir, "screenshots/blink_bmark*.jpg")

    Dir.glob(ss_path) do |ss|
      begin
        ss_time = File.mtime(ss)
        $logger.debug("demo_start: #{demo_start}, ss_time: #{ss_time}, "\
                      "demo_end: #{demo_end}, tps: #{tps}, grace:#{@grace}")
        #Status screenshot, taking withing the grace period.
        if(ss_time.between?(demo_start, demo_start + @grace))
          FileUtils.mv(ss, "#{base_name}.status.jpg")

          #Bookmark screenshot
        elsif(ss_time.between?(demo_start + @grace, demo_end - @grace))
          bmark_time_elapse = ss_time - demo_start
          tick = (bmark_time_elapse * tps ).to_i
          ss_name = File.basename(ss, ".jpg")
          message = ss_name.match(/^blink_bmark_?([a-zA-Z]+[^_]*)_?\d*$/)[1] rescue "bmark"
          message = "bmark" if message.empty?
          $logger.info("Adding bookmark to file: "\
                       "#{File.join(@move_path, "bookmark.txt")}")
          bmark_text = "#{File.basename(base_name)} : #{tick} ticks :"\
            "#{(bmark_time_elapse/60).to_i}m#{(bmark_time_elapse%60).to_i}s : "\
            "#{message}"
          $logger.info("bookmark text #{bmark_text}")
          File.open(File.join(@move_path, "bookmark.txt"), "a") do |f|
            f.puts bmark_text
          end
          #Move bookmark image to to demo file location.
          FileUtils.mv(ss, "#{base_name}.#{tick.to_s}.jpg")

          #Scoreboard screenshot, taking withing the grace period.
        elsif(ss_time.between?(demo_end - @grace, demo_end))
          FileUtils.mv(ss, "#{base_name}.scoreboard.jpg")
        end
        #Bookmarks are not worth crashing for. Log and skip if problems occur.
      rescue => e
        $logger.error("Failed to process screenshot: #{ss}")
        $logger.error(e)
      end
    end

  end

  #Handles new demo file event.
  def move_demo_file(filename)
    begin
      #Handle demo file
      demo_file_path = File.join(@demo_dir, filename)
      d = DemoFile.new(demo_file_path)
      $logger.debug d
      new_file_path = File.join(@move_path, "#{d.time_str}_#{d.map}-#{d.nick}")
      screenshot_basename = new_file_path
      new_file_path += "_#{(d.duration/60).to_i}m#{(d.duration%60).to_i}s.dem"
      puts demo_file_path + " ---> " + new_file_path
      $logger.info demo_file_path + " ---> " + new_file_path
      FileUtils.mv(demo_file_path, new_file_path)

      #Handle bookmarks
      #ticks per second
      tps = d.ticks / d.duration
      demo_start = d.time - d.duration
      demo_end = d.time
      find_and_handle_screenshots(screenshot_basename, demo_start, demo_end, tps)

    rescue => e
      $stderr.puts(e)
      $logger.error(e)
      system("zenity --text=\"Could not move demo: #{demo_file_path}\n"\
             "message: #{e.message}\" --error")
    end
  end

end

if ARGV.size ==  1
  if ARGV[0] == "--version" || ARGV[0] == "-v"
    puts "blink_record binary version #{$version}"
    exit 0
  elsif ARGV[0] == "--debug"
    $logger.level = Logger::DEBUG
  end
end

#Handles new demo file event.

begin
  blink_record = BlinkRecord.new
  i = Inotify.new

  #setup the inotify listening thread
  t = Thread.new do
    i.each_event do |ev|
      #A new demo file
      if ev.name =~ /demo_\d\d\.dem/
        $logger.info ev.inspect
        blink_record.move_demo_file(ev.name)
      end
    end
  end

  begin
    #Only show newly written closed files
    i.add_watch(blink_record.demo_dir, Inotify::CLOSE_WRITE)
  rescue => e
    $logger.error e
    system("zenity --text\"Error in inotify.\n#{e.message}\" --error")
    abort("Error in registering inotify. Aborting.")
  end

  t.join
  exit 0

rescue => e
  $logger.error(e)
  system("zenity --text\"Unexpected error.\n#{e.message}\" --error")
  abort("Unexpected error: #{e.message}")
end
